### ISSUE TITLE
pinned dependencies causing minor issues

### ISSUE THREAD

**Issue by psifertex** [toolCHAINZ/hexfiles#6]
Just a heads up that I was running into an issue where the pyreadline that was pinned in the requirements.txt was trigger a very bizarre `NameError` in `deprecated.py` about something named `x` missing. I have _no_ idea why this was the case but after a bunch of binary searching dependencies I finally realized it was due to the very specify version of pyreadline3 installed by hexfiles. It only dies for me on a specific 3.11 python with some dependencies from a homebrew python also in the mix so no idea how widespread this is. That said... just removing the pinning (I assume the result of poetry?) from the requirements seems to fix it for me so figured I'd mention it here.

**Comment by toolCHAINZ** [comment]
I've added a new version to bump a couple dependencies/remove usage of some deprecated binja APIs, and while I was at it, I took out the pins from the requirements.txt file. Curious to hear if that fixes it for you!

**Comment by psifertex** [comment]
I've moved on to a different version of python since then so it certainly has one way or the other!
